#### 1. Crea un array con 15 números enteros aleatorios entre 1 y 100


In [23]:
import numpy as np
array=np.random.randint(1,101,15,dtype=np.int16)
print(array)

[ 57  26  68  60  85 100  15  59  96  78  97  75  71   1  16]


### 2. Multiplica todos los elementos del array usando un bucle y después usando un 
### método de numpy. Compara los resultados

In [30]:
import numpy as np
array=np.random.randint(1,101,15,dtype=np.int16)
productonp=np.prod(array)
productobuc=1
for i in range(len(array)):
    productobuc*=array[i]
print(productobuc)    
print(productonp)
print(array)
if productonp==productobuc:
    print('son iguales')
else:
    print('son distintos')

1274530816
1274530816
[ 85  15  15 100  16  30  36  21  51  85  79  81  22  85   3]
son iguales


C:\Users\Usuario\AppData\Local\Temp\ipykernel_3544\3620877130.py:6: RuntimeWarning: overflow encountered in long_scalars
  productobuc*=array[i]


### 3. Crea otro array con 15 números decimales aleatorios entre 0 y 1

In [36]:
import numpy as np
array=np.random.random(15)
print(array)

[0.71111752 0.36002679 0.30631851 0.91542603 0.51146996 0.41336281
 0.3429372  0.41251876 0.07767289 0.70502388 0.94696414 0.41552187
 0.64971    0.26754453 0.82504041]


### 4. Suma los elementos de ambos arrays elementos por elemento. Resuélvelo usando un 
### operador y después con una función de numpy
### (Pista: busca en google que función de numpy hace esto)

In [39]:
import numpy as np
array_randit=np.random.randint(1,101,15,dtype=np.int16)
array_random=np.random.random(15)
#operador
sumarreyop=array_random+array_randit
#numpy func
sumarreynp=np.add(array_randit,array_random)

print(array_randit)
print(array_random)
print(sumarreyop)
print(sumarreynp)

[31  6 62 23  3 65 92 71 30 75 13 78 83 21 23]
[0.54052858 0.04731452 0.99038874 0.53847914 0.77006481 0.89396007
 0.59610692 0.51161369 0.28460595 0.56821608 0.35663426 0.11905322
 0.39774681 0.21976769 0.80649216]
[31.54052858  6.04731452 62.99038874 23.53847914  3.77006481 65.89396007
 92.59610692 71.51161369 30.28460595 75.56821608 13.35663426 78.11905322
 83.39774681 21.21976769 23.80649216]
[31.54052858  6.04731452 62.99038874 23.53847914  3.77006481 65.89396007
 92.59610692 71.51161369 30.28460595 75.56821608 13.35663426 78.11905322
 83.39774681 21.21976769 23.80649216]


### 5. Ahora réstalos. Resuélvelo usando un operador y después con una función de numpy
### (Pista: busca en google que función de numpy hace esto)

In [1]:
import numpy as np
array_randit=np.random.randint(1,101,15,dtype=np.int16)
array_random=np.random.random(15)
#operador
restarreyop=array_randit-array_random
#numpy func
restarreynp=np.subtract(array_randit,array_random)

print(array_randit)
print(array_random)
print(restarreyop)
print(restarreynp)

[96 10 90 32 84 79 23 20 76 67 11 79 23 22 68]
[0.78774939 0.0616144  0.02208434 0.8777112  0.911615   0.84810435
 0.71817531 0.85231134 0.35022239 0.09454702 0.3740062  0.00772293
 0.01812544 0.71797528 0.43269999]
[95.21225061  9.9383856  89.97791566 31.1222888  83.088385   78.15189565
 22.28182469 19.14768866 75.64977761 66.90545298 10.6259938  78.99227707
 22.98187456 21.28202472 67.56730001]
[95.21225061  9.9383856  89.97791566 31.1222888  83.088385   78.15189565
 22.28182469 19.14768866 75.64977761 66.90545298 10.6259938  78.99227707
 22.98187456 21.28202472 67.56730001]


### 6. Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y 
### después con una función de numpy 
### (Pista: busca en google que función de numpy hace esto)

In [8]:
import numpy as np
array_randit = np.random.randint(1,101,15,dtype=np.int16)
array_random = np.random.random(15)
Arraymultbuc = np.zeros(15)

#bucle
for i in range(15):
    Arraymultbuc[i]=array_randit[i]*array_random[i]
#np
arraymultnp=np.multiply(array_randit,array_random)
print(Arraymultbuc)
print(arraymultnp)
    

[ 3.55715642  5.90135278 15.94310037  0.54621335 76.3415971  52.18130865
 13.067968   28.27666577 22.19465875 15.00179876 19.60051651  2.77359912
 37.2573852  20.93491914 58.49419274]
[ 3.55715642  5.90135278 15.94310037  0.54621335 76.3415971  52.18130865
 13.067968   28.27666577 22.19465875 15.00179876 19.60051651  2.77359912
 37.2573852  20.93491914 58.49419274]


### 7. Encuentra el valor más alto del primer array que has creado. 

In [7]:
import numpy as np
array_randit = np.random.randint(1,101,15,dtype=np.int16)
print(array_randit)
print(max(array_randit))

[28  6 89 23 28 21 55 34  7 70 49  6 67 51  1]
89


### 8. Calcula la media (mean), la mediana (median) y al deviación estandar (standard 
### deviation) de los arrays (Nota: No nos importa el significado matemático de estos 
### valores, lo importante es que encuentres que función de numpy necesitas. Puedes 
### hacer la búsqueda en castellano o en inglés, aunque en inglés muchas veces suele 
### haber más resultados).
